<?php
$geologicals = [
    "Geyser",
    "Fumarole",
    "Lava Spout",
    "Ice Fumarole",
    "Ice Geyser",
    "Gas Vent"
];

// all the species of bios in an array for matching
$species = [
"Geyser",
"Albidum Sinuous Tubers",
"Aleoida Arcus",
"Aleoida Coronamus",
"Aleoida Spica",
"Aleoida Laminiae",
"Aleoida Gravis",
"Amphora Plant",
"Aureum Brain Tree",
"Bacterium Aurasus",
"Bacterium Nebulus",
"Bacterium Scopulum",
"Bacterium Acies",
"Bacterium Vesicula",
"Bacterium Alcyoneum",
"Bacterium Tela",
"Bacterium Informem",
"Bacterium Volu",
"Bacterium Bullaris",
"Bacterium Omentum",
"Bacterium Cerbrus",
"Bacterium Verrata",
"Bark Mounds",
"Blatteum Bioluminescent Anemone",
"Blatteum Sinuous Tubers",
"Cactoida Cortexum",
"Cactoida Lapis",
"Cactoida Vermis",
"Cactoida Pullulanta",
"Cactoida Peperatis",
"Clypeus Lacrimam",
"Clypeus Margaritus",
"Clypeus Speculumi",
"Concha Renibus",
"Concha Aureolas",
"Concha Labiata",
"Concha Biconcavis",
"Crystalline Shards",
"Common Thargoid Barnacle",
"Croceum Anemone",
"Electricae Pluma",
"Electricae Radialem",
"Fonticulua Segmentatus",
"Fonticulua Campestris",
"Fonticulua Upupam",
"Fonticulua Lapida",
"Fonticulua Fluctus",
"Fonticulua Digitos",
"Fumerola Carbosis",
"Fumerola Extremus",
"Fumerola Nitris",
"Fumerola Aquatis",
"Fungoida Setisis",
"Fungoida Stabitis",
"Fungoida Bullarum",
"Fungoida Gelata",
"Gypseeum Brain Tree",
"Large Thargoid Barnacle",
"Lindigoticum Brain Tree",
"Lividum Brain Tree",
"Lindigoticum Sinuous Tubers",
"Luteolum Anemone",
"Osseus Fractus",
"Osseus Discus",
"Osseus Spiralis",
"Osseus Pumice",
"Osseus Cornibus",
"Osseus Pellebantus",
"Ostrinum Brain Tree",
"Prasinum Bioluminescent Anemone",
"Prasinum Sinuous Tubers",
"Puniceum Anemone",
"Puniceum Brain Tree",
"Recepta Umbrux",
"Recepta Deltahedronix",
"Recepta Conditivus",
"Roseum Anemone",
"Roseum Brain Tree",
"Roseum Bioluminescent Anemone",
"Rubeum Bioluminescent Anemone",
"Roseum Sinuous Tubers",
"Stratum Excutitus",
"Stratum Paleas",
"Stratum Laminamus",
"Stratum Araneamus",
"Stratum Limaxus",
"Stratum Cucumisis",
"Stratum Tectonicas",
"Stratum Frigus",
"Tubus Conifer",
"Tubus Sororibus",
"Tubus Cavas",
"Tubus Rosarium",
"Tubus Compagibus",
"Frutexa Flabellum",
"Frutexa Acus",
"Frutexa Metallicum",
"Frutexa Flammasis",
"Frutexa Fera",
"Frutexa Sponsae",
"Frutexa Collum",
"Tussock Pennata",
"Tussock Ventusa",
"Tussock Ignis",
"Tussock Cultro",
"Tussock Catena",
"Tussock Pennatis",
"Tussock Serrati",
"Tussock Albata",
"Tussock Propagito",
"Tussock Divisa",
"Tussock Caputus",
"Tussock Triticum",
"Tussock Stigmasis",
"Tussock Virgam",
"Tussock Capillum",
"Unknown",
"Violaceum Sinuous Tubers",
"Viride Brain Tree",
"Viride Sinuous Tubers"
];